[tool.poetry]
name = "selenium"
version = "0.1.0"
description = ""
authors = ["rapport87 <rapport87@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
